In [2]:
!pip install nltk
!pip install pandas
import nltk
import pandas as pd
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.stem import PorterStemmer

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in c:\users\divya\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\divya\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in c:\users\divya\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\divya\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\divya\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\divya\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\divya\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\divya\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\divya\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\divya\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\divya\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\divya\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Divya\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Divya\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Divya\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [7]:
df=pd.read_csv('twitter_training.csv')
df

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...
...,...,...,...,...
74676,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74677,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74678,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74679,9200,Nvidia,Positive,Just realized between the windows partition of...
74680,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

In [8]:
df.rename(columns={list(df)[0]:'TweetID',
                   list(df)[1]:'Entity',
                      list(df)[2]:'Sentiment',
                      list(df)[3]:'Tweet'},inplace=True)

In [10]:
df.describe()

            TweetID
count  74681.000000
mean    6432.640149
std     3740.423819
min        1.000000
25%     3195.000000
50%     6422.000000
75%     9601.000000
max    13200.000000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74681 entries, 0 to 74680
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TweetID    74681 non-null  int64
 1   Entity     74681 non-null  object
 2   Sentiment  74681 non-null  object
 3   Tweet      73995 non-null  object
dtypes: int64(1), object(3)
memory usage: 2.3+ MB

In [12]:
df = df.drop(columns='TweetID')

In [13]:
df.isnull().sum()

Entity         0
Sentiment      0
Tweet        686
dtype: int64

In [14]:
import re
cleaned=[]
for txt in df['Tweet']:
    # Convert txt to string and handle NaN values
    txt = str(txt) if not pd.isna(txt) else ''
    cleaned_text = re.sub(r'[^\w\s]', '', txt)  # Removes everything except word characters and spaces
    cleaned_text = re.sub(r'\s+', ' ', cleaned_text)  # Replaces multiple spaces with a single space
    cleaned_data=cleaned_text.strip()  # Removes leading/trailing whitespace
    cleaned.append(cleaned_data)
cleaned

['I am coming to the borders and I will kill you all',
 'im getting on borderlands and i will kill you all',
 'im coming on borderlands and i will murder you all',
 'im getting on borderlands 2 and i will murder you me all',
 'im getting into borderlands and i can murder you all',
 'So I spent a few hours making something for fun If you dont know I am a HUGE Borderlands fan and Maya is one of my favorite characters So I decided to make myself a wallpaper for my PC Here is the original image versus the creation I made Enjoy pictwittercommLsI5wf9Jg',
 'So I spent a couple of hours doing something for fun If you dont know that Im a huge Borderlands fan and Maya is one of my favorite characters I decided to make a wallpaper for my PC Heres the original picture compared to the creation I made Have fun pictwittercom mLsI5wf9Jg',
 'So I spent a few hours doing something for fun If you dont know Im a HUGE Borderlands fan and Maya is one of my favorite characters',
 'So I spent a few hours making something for fun If you dont know I am a HUGE RhandlerR fan and Maya is one of my favorite characters So I decided to make myself a wallpaper for my PC Here is the original image versus the creation I made Enjoy pictwittercommLsI5wf9Jg',
 '2010 So I spent a few hours making something for fun If you dont know I am a HUGE RhandlerR fan and Maya is one of my favorite characters So I decided to make myself a wallpaper for my PC Here is the original image versus the creation I made Enjoy pictwittercommLsI5wf9Jg',
 'was',
 'RockHard La Varlope RARE POWERFUL HANDSOME JACKPOT Borderlands 3 Xbox dlvritRMTrgF',
 'RockHard La Varlope RARE POWERFUL HANDSOME JACKPOT Borderlands 3 Xbox dlvrit RMTrgF',
 'RockHard La Varlope RARE POWERFUL HANDSOME JACKPOT Borderlands 3 Xbox dfrit RMTrgF',
 'RockHard La Vita RARE BUT POWERFUL HANDSOME JACKPOT Borderlands 1 Xbox dlvritRMTrgF',
 'Live Rock Hard music La la Varlope RARE the POWERFUL Live HANDSOME i JACKPOT Borderlands 3 Sega Xbox dlvr From it e RMTrgF',
 'IHard like me RARE LONDON DE HANDSOME 2011 Borderlands 3 Xbox dlvritRMTrgF',
 'that was the first borderlands session in a long time where i actually had a really satisfying combat experience i got some really good kills',
 'this was the first Borderlands session in a long time where i actually had a really satisfying fighting experience i got some really good kills',
 'that was the first borderlands session in a long time where i actually had a really satisfying combat experience i got some really good kills',
 'that was the first borderlands session in a long time where i actually enjoyed a really satisfying combat experience i got some rather good kills',
 'that I was the first real borderlands session in a nice long wait time where i actually had a really satisfying combat experience and i got some really good kills',
 'that was the first borderlands session in a hot row where i actually had a really bad combat experience i did some really good kills',
 'the biggest dissappoinment in my life came out a year ago fuck borderlands 3',
 'The biggest disappointment of my life came a year ago',
 'The biggest disappointment of my life came a year ago',
 'the biggest dissappoinment in my life coming out a year ago fuck borderlands 3',
 'For the biggest male dissappoinment in my life came hanging out a year time ago fuck borderlands 3',
 'the biggest dissappoinment in my life came back last year ago fuck borderlands last',
 'WE FINISHED BORDERLANDS 3 FINALLY YAS Thank you for hanging out everyone It was fun I will try to stream tomorrow but if not I might so some IRL streams while awayu We shall see Thank you so much for the raids mompou_mumpow MegaMagwitch and KfdMitch',
 'WE FINALLY FINALLY FIND BORDERLANDS 3 YES Thank you all for hanging out It was fun Ill try to stream tomorrow but if not maybe some IRL streams Well see Thanks for the raids mompou _ mumpow MegaMagwitch and KfdMitch',
 'Thank you for hanging up everyone It was fun Ill try to get a haircut tomorrow but if it wasnt for me some IRL streams would still be in Hawaii Well see Thank you so much for the mompou _ mumpow MegaMagwife and fendMitch raids',
 'WE FINISHED BORDERLANDS 3 UPDATE YAS Thank you for hanging out guys It was fun I will try to stream and even if not I might so some IRL streams while awayu We shall go Thank you so much for the raids mompou_mumpow MegaMagwitch and Hope',
 'WE FINISHED BORDERLANDS 3 AND FINALLY YAS Thank you everyone for hanging out everyone It was fun I will try to make stream tomorrow but if not I might make so some IRL streams while awayu 10 We never shall see Thank you both so much for the raids mompou_mumpow or MegaMagwitch and 4 KfdMitch',
 'WE FINISHED BORDERLANDS 3 FINALLY YAS Hey you for hanging out so It was fun I will try that stream tomorrow and if not I might use some IRL streams from awayu We shall see Thank you so much how many raids mompou_mumpow did and their',
 'Man Gearbox really needs to fix this dissapointing drops in the new Borderlands 3 DLC cant be fine to farm bosses on Mayhem 10 to get 1 legendary drop while anywhere else i get 610 drops Really sucks alot',
 'Man Gearbox really needs to fix these disappointing drops in the new Borderlands 3 DLC for farm bosses on Mayhem 10 to get a legendary drop while I get 610 drops elsewhere',
 'Man Gearbox really needs to fix this disssapointing drops in the new Borderlands 3 DLC cant be fine to farm bosses on Mayhem 10 to get 1 legendary drop while elsewhere i get 610 drops Really sucks alot',
 'Man Bethesda really needs to fix this dissapointing drops and the new Borderlands 3 It cant be fine to farm bosses on Mayhem 10 to get 1 legendary drop while anywhere else i get 610 drops Really sucks',
 'Man Gearbox really needs to fix this dissapointing drops in the completely new Borderlands 3 Days DLC i cant e be fine having to be farm bosses on Mayhem 10 to e get 1 legendary foot drop while anywhere else i get 6 10 drops It Really sucks to alot',
 'unk Gearbox really time to fix this 10 drops in the new Borderlands 3 DLC or be fine to force bosses on Mayhem 10 to get a legendary drop while everyone else i get 610 drops Really needs alot',
 'Check out this epic streamer',
 'Check out this epic streamer',
 'Watch this epic striptease',
 'Check out our epic streamer',
 'Check out this big epic streamer',
 'Checkunk this epic streamer',
 'Blaming Sight for Tardiness A little bit of borderlands I got called in early for work tomorrow so I cant make up time Sorry my loves twitchtvpunnisenpai',
 'A bit of borderland I was called to work tomorrow morning so I cant catch up Sorry my love twitchtv punnisenpai',
 'Guilty of sobriety A bit of a borderline I was called to work early tomorrow so I cant catch up',
 'Blaming Sight for Tardiness A little bit of borderlands I got called in early for work tomorrow so I cant make up time Sorry my loves twitchtvpunnisenpai',
 'for Blaming Sight for Tardiness A little bit of borderlands I got called in early for work tomorrow so I cant make up time Sorry my loves twitchtvpunnisenpai',
 'all',
 'why does like every man in borderlands have slicked back hair havent you heard of bangs you stupid assholes',
 'Why like every man in border countries have you not heard of bangs you stupid assholes',
 'Why like everyone else in the border countries have your hair fallen off have you not heard that you are stupid aliens',
 'why does likeunk man in borderlands have slicked back hair or you heard of bangs you stupid assholes',
 'why Beth does like every man in borderlands have she slicked that back hair haven t you heard enough of gray bangs you stupid assholes',
 'why does practically every man in France have slicked back hair havent you heard of bangs the greedy assholes',
 '',
 '',
 '',
 '45',
 '',
 'what',
 'Going to finish up Borderlands 2 today Ive got some new commands set up and am looking forward to a good stream Starting in about am hour',
 'I will finish Borderlands 2 today I have some new commands set up and am looking forward to a good stream Start in about an hour',
 'Im going to finish Borderlands 2 today I have some new commands installed and Im looking forward to a good stream',
 'Going to finish up Borderlands 2 today Ive got some new events set up and am look forward to a good stream Starting in about 20 hour',
 'Going to finish finish cleaning up Borderlands 2 today Ive just got her some new commands set all up and am looking forward it to a good stream Starting in about am hour',
 'Going to finish up volume 2 today Ive got some awesome server set up and is looking forward to a good stream Starting in about am hour',
 'imma probably play some borderlands tps in a bit thatll be fun',
 'imma is probably playing a bit of borderland tps That will be fun',
 'imma will probably play some border tps in a bit Its going to be fun',
 'imma probably play live borderlands tps in a bit thatll be fun',
 'for imma probably play some borderlands tps in a bit thatyer ll be a fun',
 'imma probably got some video tps in a bit thatll make fun',
 'One of our own ProfZeroo is live w borderlands 3 Catch him here buffly2WmmiP5 Say Streamer Shouts in chat for a chance to be in a coming streamer_shouts Shout Out',
 'One of our own ProfZeroo is live w borderlands 3 catch him here buffly 2WmmiP5 Say Streamer Shouts in chat for a chance to be in an upcoming one streamer _ shouts Shout Out',
 'One of our own ProfZero live w borderlands 3 Catch him here buffly 2WmmiP5 Say Stream Shouts in chat for a chat for a chance to be in a coming stream _ Shouts Shout Out',
 'One of our own ProfZeroo is live borderlands 3 Catch him here buffly2WmmiP5 p Say some Shouts in chat a chance to be in a coming Also Shout Out',
 'One of our shows own ProfZeroo is live via w at borderlands 3 and UNK Catch him here the buff ly to 2WmmiP5 to Say Streamer Shouts in chat for a chance to officially be in a series coming streamer_shouts 1 Shout Out',
 'One of its own movies is live w ProfZeroo 3 Catch him from buffly2WmmiP5 for Streamer Shouts in invitation or a chance to be out a coming All 3 invites',
 'FUCK YESSSSSSSS',
 'FICK YESSSSSS',
 'FUCK YESSSSSSSS',
 'FUCK YESSSSSSSSunk',
 'A FUCK YESSSSSSSS',
 'FUCK YOU',
 'I hate that this easy mayhem modifier event on mayhem wont last forever this is the most fun ive had in the game since they added them horrible modifiers Borderlands please give me the option to play mayhem 10 but turn the modifiers off PLS',
 'I hate that this simple Chaos Modifier event on Chaos wont last forever Thats the most fun Ive had in the game since they added terrible modifiers Borderlands please give me the option to play Chaos 10 but turn off the modifiers',
 'I hate that this easy mayhem modifier event on mayhem wont last forever this is the most fun ive had in the game since they added them horrible modifiers Borderlands please give me the option to play mayhem 10 but turn the modifiers off PLS',
 'I hate saying this easy day 9 event on mayhem wont last forever this is the most fun ive had in the game since they added them horrible modifiers Borderlands please give me some ability to play mayhem 10 but turn the modifiers off PLS',
 'I hate thinking that this easy mayhem modifier event on total mayhem won t last forever this is the absolutely most ridiculous fun experience i ve had in the game almost since they added them horrible modifiers Borderlands please do give me the option option to a play mayhem 10 but turn the modifiers off PLS',
 'I hate that this easy horrible modifier event on game 10 last forever That is the best fun ive taken in the past until they added them horrible modifiers Borderlands please send me the option to play mayhem 10 but turn the modifiers for PLS',
 'Grounded almost looked pretty cool even despite the borderlands tier unfunny writing until it became yet another survival crafting game I really cant wait for this shitty trend to die',
 'Grounded looked cool despite the borderline unfunny writing until it became another survival crafting game I really cant wait for this crappy trend to die',
 'Grosskreutz looked pretty cool even despite the unfunny spelling until it turned into another survival game I really cant wait for this crap trend to die',
 'Grounded almost looked pretty cool here despite the borderlands tier unfunny writing until it became yet an survival crafting game I really cant wait for this shitty mod to die',
 'Deep Grounded almost looked pretty cool even despite the borderlands fifth tier unfunny writing format until ultimately it became yet another survival crafting mobile game I really can t wait for this shitty trend starting to die',
 'Grounded almost was pretty cool even despite the top tier unfunny writing until we became yet another annoying crafting game I seriously cant wait on this shitty trend to die',
 'Appreciate the sonic concepts praxis Valenzuela and LandaPosas thread together in this talk multimodal listening soundwalks borderlands frameworks participatory action research and testimonios So many thoughtful and resonant intersections here',
 'Appreciate the sound concepts practices that Valenzuela and LandaPosas combine in this lecture multimodal listening soundwalks borderland frameworks participatory action research and testimonies So many thoughtful and resonant intersections here',
 'Evaluate the sound concepts concepts of Valensela and Landa Pozas together in this conversation multimodal listening walks border areas joint action studies etc So many amazing and resonant intersections here',
 'Appreciate the sonic concepts praxis Valenzuela and MorenoPosas have together in this talk multimodal listening soundwalks borderlands recordings participatory field research and testimonios So many thoughtful and resonant intersections here',
 'Appreciate by the sonic electronic concepts praxis Valenzuela and Landa Posas do thread together together in creating this talk multimodal visual listening digital soundwalks borderlands frameworks participatory action research interviews and testimonios So many thoughtful thoughts and resonant intersections reflected here',
 'Appreciate the sonic conversations actions Klein and LandaPosas brought together in our talk multimodal experiences soundwalks ethical frameworks participatory action practices and testimonios So many provocative and resonant intersections today',
 'Borderlands how do I submit a complaint Your CEO isnt paying his staff their bonuses',
 'Borderlands how can I file a complaint Your CEO doesnt pay his employees their bonuses',
 'Borderlands how to file a complaint Your CEO doesnt pay his employees bonuses',
 'Borderlands how did I submit a complaint Your CEO isnt paying his competitors their bonuses',
 'Borderlands how do suppose I submit a complaint Your CEO isnain t even paying his entire staff their bonuses',
 'Now how do I submit any complaint Your CEO isnt offering his staff their bonuses',
 'All the Borderlands are fuckin trash',
 'All the Borderlands are damn rubbish',
 'All the borderlands are fucking thrash',
 'All the Borderlands shit fuckin trash',
 '35 All the Borderlands are fuckin trash',
 'All the Borderlands are fuckin stupid',
 'Finally played through borderlands 3 The actual game play is great Almost all guns feel fun and I never once felt like I needed to grind That story on the other hand All I will say Is that Im very much so looking forward to the eventual cutscene skip',
 'Finally played by Borderlands 3 The actual game is great Almost all weapons feel funny and I never felt like I had to grind On the other hand All I will say is that I am very much looking forward to the eventual sequence skip',
 'This story on the other hand All I will say is that Im looking forward to an occasional slip',
 'Finally played through borderlands 3 The open game play is great Almost all guns feel fun and I never once felt like I needed to grind The story on to another hand All I will say Is that Im very much so looking forward to its eventual cutscene skip',
 'Finally played through borderlands 3 The actual game I play is great Almost all guns feel fun and yet I never once felt much like someone I seriously needed to grind That pretty story on the other side hand All I will say Is that Im very damn much so forward looking forward to the eventual endless cutscene skip',
 'Finally played through borderlands 5 The actual game play is great Almost all guns were fun and I never once felt sure I needed to grind That story is the other hand but I will say now oh yesm very much so looking forward to the extended cutscene skip',
 'Loving these new GhostLifestyle cans Anyone else drink Ghost',
 'I love these new GhostLifestyle cans Everyone else drinks ghost',
 'Love these new GhostLive cans Does anyone else drink Ghost',
 'Loving these new GhostLifestyle cans Anyone else drink Ghost',
 'Loving back these three new GhostLifestyle cans By Anyone else else drink Ghost',
 'do these new GhostLifestyleunk They want drink Ghost',
 'Come meet one of the lovely Gaming Goddesses',
 'Meet one of the lovely gambling goddesses',
 'Come meet one of the beautiful gods of gambling',
 'Come to one of the lovely Gaming Goddesses',
 '16 Come meet one of the lovely Gaming Goddesses',
 'Come meet one of the lovely Green Goddesses',
 'How the hell are we into Halloween month already',
 'How the hell are we already into Halloween month',
 'How the hell are we already in Halloween month',
 'How the hell are March into Halloween month already',
 'How the hell are pulling we into Halloween month starting already',
 'in the hell are we into Halloween month already',
 'What a bitch',
 'What a slut',
 'What a bitch',
 'What terrible bitch',
 'What a bitch',
 'What a miracle',
 'Ok I am LOVING THIS also playing Bombs Over Baghdad in anything gets me hype Very Borderlands like and the concept is A1',
 'Ok Im LOVING THIS also playing Bombs Over Baghdad in something gives me a hype Very Borderlands like and the concept is A1',
 'Ok I am LOVING THIS also playing Bombs Over Baghad in anything gets me here Very Borderlands like and the concept is A1',
 'Ok I am LOVING THIS also seeing Take Over Baghdad in anything gets me hype Very Borderlands like and the concept is awesome',
 'Ok sir I am LOVING THIS also just playing Bombs Over Baghdad and in case anything gets its me hype I Very Borderlands like and the concept is A1',
 'Ok I am LOVING THIS also playing Bombs and Earth in anything gets me hype Very good RPG and the concept is A1',
 'Just uninstalled all of my other games to make space for Borderlands 3',
 'Just uninstall all my other games to make room for Borderlands 3',
 'Just deleted all my other games to make room for Borderlands 3',
 'Just uninstalled all of my other games will make space for Borderlands 3',
 'Just uninstalled all other of my my other games to make space for watching Borderlands 3',
 'Just uninstalled all of all other games in make space for Borderlands 3',
 'Already loving Bleeding Edge what a clever game Cross between Overwatch Borderlands and Domination game mode Cool as',
 'I love Bleeding Edge what a clever game Crossroads of Overwatch Borderlands and Domination game mode Cool as',
 'Cross between Overwatch Borderlands and Domination game mode Cool as',
 'Already loving Bleeding Edge what a fun game Cross between Overwatch Borderlands and Xbox game mode Cool as',
 'Already also loving the Bleeding Edge what is a clever game Cross between Overwatch Borderlands and Future Domination game mode 2016 Cool out as',
 'Already played Bleeding Edge what a clever game Cross between fantasy Borderlands non Domination game mode Playing as',
 'Bioshock AND borderlands coming to the switch bitch count me the fuck in',
 'Bioshock AND borderlands coming to the switch bitch count me the fuck in',
 'Bioshock And borderlands coming to the switch bitch count me the fuck in',
 'Bioshock AND borderlands coming to the desert bitch count me the fuck in',

In [15]:
tokens=[]
for txt in cleaned:
  p=sent_tokenize(txt)
  tokens.append(p)
tokens

[['I am coming to the borders and I will kill you all'],
 ['im getting on borderlands and i will kill you all'],
 ['im coming on borderlands and i will murder you all'],
 ['im getting on borderlands 2 and i will murder you me all'],
 ['im getting into borderlands and i can murder you all'],
 ['So I spent a few hours making something for fun If you dont know I am a HUGE Borderlands fan and Maya is one of my favorite characters So I decided to make myself a wallpaper for my PC Here is the original image versus the creation I made Enjoy pictwittercommLsI5wf9Jg'],
 ['So I spent a couple of hours doing something for fun If you dont know that Im a huge Borderlands fan and Maya is one of my favorite characters I decided to make a wallpaper for my PC Heres the original picture compared to the creation I made Have fun pictwittercom mLsI5wf9Jg'],
 ['So I spent a few hours doing something for fun If you dont know Im a HUGE Borderlands fan and Maya is one of my favorite characters'],
 ['So I spent a few hours making something for fun If you dont know I am a HUGE RhandlerR fan and Maya is one of my favorite characters So I decided to make myself a wallpaper for my PC Here is the original image versus the creation I made Enjoy pictwittercommLsI5wf9Jg'],
 ['2010 So I spent a few hours making something for fun If you dont know I am a HUGE RhandlerR fan and Maya is one of my favorite characters So I decided to make myself a wallpaper for my PC Here is the original image versus the creation I made Enjoy pictwittercommLsI5wf9Jg'],
 ['was'],
 ['RockHard La Varlope RARE POWERFUL HANDSOME JACKPOT Borderlands 3 Xbox dlvritRMTrgF'],
 ['RockHard La Varlope RARE POWERFUL HANDSOME JACKPOT Borderlands 3 Xbox dlvrit RMTrgF'],
 ['RockHard La Varlope RARE POWERFUL HANDSOME JACKPOT Borderlands 3 Xbox dfrit RMTrgF'],
 ['RockHard La Vita RARE BUT POWERFUL HANDSOME JACKPOT Borderlands 1 Xbox dlvritRMTrgF'],
 ['Live Rock Hard music La la Varlope RARE the POWERFUL Live HANDSOME i JACKPOT Borderlands 3 Sega Xbox dlvr From it e RMTrgF'],
 ['IHard like me RARE LONDON DE HANDSOME 2011 Borderlands 3 Xbox dlvritRMTrgF'],
 ['that was the first borderlands session in a long time where i actually had a really satisfying combat experience i got some really good kills'],
 ['this was the first Borderlands session in a long time where i actually had a really satisfying fighting experience i got some really good kills'],
 ['that was the first borderlands session in a long time where i actually had a really satisfying combat experience i got some really good kills'],
 ['that was the first borderlands session in a long time where i actually enjoyed a really satisfying combat experience i got some rather good kills'],
 ['that I was the first real borderlands session in a nice long wait time where i actually had a really satisfying combat experience and i got some really good kills'],
 ['that was the first borderlands session in a hot row where i actually had a really bad combat experience i did some really good kills'],
 ['the biggest dissappoinment in my life came out a year ago fuck borderlands 3'],
 ['The biggest disappointment of my life came a year ago'],
 ['The biggest disappointment of my life came a year ago'],
 ['the biggest dissappoinment in my life coming out a year ago fuck borderlands 3'],
 ['For the biggest male dissappoinment in my life came hanging out a year time ago fuck borderlands 3'],
 ['the biggest dissappoinment in my life came back last year ago fuck borderlands last'],
 ['WE FINISHED BORDERLANDS 3 FINALLY YAS Thank you for hanging out everyone It was fun I will try to stream tomorrow but if not I might so some IRL streams while awayu We shall see Thank you so much for the raids mompou_mumpow MegaMagwitch and KfdMitch'],
 ['WE FINALLY FINALLY FIND BORDERLANDS 3 YES Thank you all for hanging out It was fun Ill try to stream tomorrow but if not maybe some IRL streams Well see Thanks for the raids mompou _ mumpow MegaMagwitch and KfdMitch'],
 ['Thank you for hanging up everyone It was fun Ill try to get a haircut tomorrow but if it wasnt for me some IRL streams would still be in Hawaii Well see Thank you so much for the mompou _ mumpow MegaMagwife and fendMitch raids'],
 ['WE FINISHED BORDERLANDS 3 UPDATE YAS Thank you for hanging out guys It was fun I will try to stream and even if not I might so some IRL streams while awayu We shall go Thank you so much for the raids mompou_mumpow MegaMagwitch and Hope'],
 ['WE FINISHED BORDERLANDS 3 AND FINALLY YAS Thank you everyone for hanging out everyone It was fun I will try to make stream tomorrow but if not I might make so some IRL streams while awayu 10 We never shall see Thank you both so much for the raids mompou_mumpow or MegaMagwitch and 4 KfdMitch'],
 ['WE FINISHED BORDERLANDS 3 FINALLY YAS Hey you for hanging out so It was fun I will try that stream tomorrow and if not I might use some IRL streams from awayu We shall see Thank you so much how many raids mompou_mumpow did and their'],
 ['Man Gearbox really needs to fix this dissapointing drops in the new Borderlands 3 DLC cant be fine to farm bosses on Mayhem 10 to get 1 legendary drop while anywhere else i get 610 drops Really sucks alot'],
 ['Man Gearbox really needs to fix these disappointing drops in the new Borderlands 3 DLC for farm bosses on Mayhem 10 to get a legendary drop while I get 610 drops elsewhere'],
 ['Man Gearbox really needs to fix this disssapointing drops in the new Borderlands 3 DLC cant be fine to farm bosses on Mayhem 10 to get 1 legendary drop while elsewhere i get 610 drops Really sucks alot'],
 ['Man Bethesda really needs to fix this dissapointing drops and the new Borderlands 3 It cant be fine to farm bosses on Mayhem 10 to get 1 legendary drop while anywhere else i get 610 drops Really sucks'],
 ['Man Gearbox really needs to fix this dissapointing drops in the completely new Borderlands 3 Days DLC i cant e be fine having to be farm bosses on Mayhem 10 to e get 1 legendary foot drop while anywhere else i get 6 10 drops It Really sucks to alot'],
 ['unk Gearbox really time to fix this 10 drops in the new Borderlands 3 DLC or be fine to force bosses on Mayhem 10 to get a legendary drop while everyone else i get 610 drops Really needs alot'],
 ['Check out this epic streamer'],
 ['Check out this epic streamer'],
 ['Watch this epic striptease'],
 ['Check out our epic streamer'],
 ['Check out this big epic streamer'],
 ['Checkunk this epic streamer'],
 ['Blaming Sight for Tardiness A little bit of borderlands I got called in early for work tomorrow so I cant make up time Sorry my loves twitchtvpunnisenpai'],
 ['A bit of borderland I was called to work tomorrow morning so I cant catch up Sorry my love twitchtv punnisenpai'],
 ['Guilty of sobriety A bit of a borderline I was called to work early tomorrow so I cant catch up'],
 ['Blaming Sight for Tardiness A little bit of borderlands I got called in early for work tomorrow so I cant make up time Sorry my loves twitchtvpunnisenpai'],
 ['for Blaming Sight for Tardiness A little bit of borderlands I got called in early for work tomorrow so I cant make up time Sorry my loves twitchtvpunnisenpai'],
 ['all'],
 ['why does like every man in borderlands have slicked back hair havent you heard of bangs you stupid assholes'],
 ['Why like every man in border countries have you not heard of bangs you stupid assholes'],
 ['Why like everyone else in the border countries have your hair fallen off have you not heard that you are stupid aliens'],
 ['why does likeunk man in borderlands have slicked back hair or you heard of bangs you stupid assholes'],
 ['why Beth does like every man in borderlands have she slicked that back hair haven t you heard enough of gray bangs you stupid assholes'],
 ['why does practically every man in France have slicked back hair havent you heard of bangs the greedy assholes'],
 [],
 [],
 [],
 ['45'],
 [],
 ['what'],
 ['Going to finish up Borderlands 2 today Ive got some new commands set up and am looking forward to a good stream Starting in about am hour'],
 ['I will finish Borderlands 2 today I have some new commands set up and am looking forward to a good stream Start in about an hour'],
 ['Im going to finish Borderlands 2 today I have some new commands installed and Im looking forward to a good stream'],
 ['Going to finish up Borderlands 2 today Ive got some new events set up and am look forward to a good stream Starting in about 20 hour'],
 ['Going to finish finish cleaning up Borderlands 2 today Ive just got her some new commands set all up and am looking forward it to a good stream Starting in about am hour'],
 ['Going to finish up volume 2 today Ive got some awesome server set up and is looking forward to a good stream Starting in about am hour'],
 ['imma probably play some borderlands tps in a bit thatll be fun'],
 ['imma is probably playing a bit of borderland tps That will be fun'],
 ['imma will probably play some border tps in a bit Its going to be fun'],
 ['imma probably play live borderlands tps in a bit thatll be fun'],
 ['for imma probably play some borderlands tps in a bit thatyer ll be a fun'],
 ['imma probably got some video tps in a bit thatll make fun'],
 ['One of our own ProfZeroo is live w borderlands 3 Catch him here buffly2WmmiP5 Say Streamer Shouts in chat for a chance to be in a coming streamer_shouts Shout Out'],
 ['One of our own ProfZeroo is live w borderlands 3 catch him here buffly 2WmmiP5 Say Streamer Shouts in chat for a chance to be in an upcoming one streamer _ shouts Shout Out'],
 ['One of our own ProfZero live w borderlands 3 Catch him here buffly 2WmmiP5 Say Stream Shouts in chat for a chat for a chance to be in a coming stream _ Shouts Shout Out'],
 ['One of our own ProfZeroo is live borderlands 3 Catch him here buffly2WmmiP5 p Say some Shouts in chat a chance to be in a coming Also Shout Out'],
 ['One of our shows own ProfZeroo is live via w at borderlands 3 and UNK Catch him here the buff ly to 2WmmiP5 to Say Streamer Shouts in chat for a chance to officially be in a series coming streamer_shouts 1 Shout Out'],
 ['One of its own movies is live w ProfZeroo 3 Catch him from buffly2WmmiP5 for Streamer Shouts in invitation or a chance to be out a coming All 3 invites'],
 ['FUCK YESSSSSSSS'],
 ['FICK YESSSSSS'],
 ['FUCK YESSSSSSSS'],
 ['FUCK YESSSSSSSSunk'],
 ['A FUCK YESSSSSSSS'],
 ['FUCK YOU'],
 ['I hate that this easy mayhem modifier event on mayhem wont last forever this is the most fun ive had in the game since they added them horrible modifiers Borderlands please give me the option to play mayhem 10 but turn the modifiers off PLS'],
 ['I hate that this simple Chaos Modifier event on Chaos wont last forever Thats the most fun Ive had in the game since they added terrible modifiers Borderlands please give me the option to play Chaos 10 but turn off the modifiers'],
 ['I hate that this easy mayhem modifier event on mayhem wont last forever this is the most fun ive had in the game since they added them horrible modifiers Borderlands please give me the option to play mayhem 10 but turn the modifiers off PLS'],
 ['I hate saying this easy day 9 event on mayhem wont last forever this is the most fun ive had in the game since they added them horrible modifiers Borderlands please give me some ability to play mayhem 10 but turn the modifiers off PLS'],
 ['I hate thinking that this easy mayhem modifier event on total mayhem won t last forever this is the absolutely most ridiculous fun experience i ve had in the game almost since they added them horrible modifiers Borderlands please do give me the option option to a play mayhem 10 but turn the modifiers off PLS'],
 ['I hate that this easy horrible modifier event on game 10 last forever That is the best fun ive taken in the past until they added them horrible modifiers Borderlands please send me the option to play mayhem 10 but turn the modifiers for PLS'],
 ['Grounded almost looked pretty cool even despite the borderlands tier unfunny writing until it became yet another survival crafting game I really cant wait for this shitty trend to die'],
 ['Grounded looked cool despite the borderline unfunny writing until it became another survival crafting game I really cant wait for this crappy trend to die'],
 ['Grosskreutz looked pretty cool even despite the unfunny spelling until it turned into another survival game I really cant wait for this crap trend to die'],
 ['Grounded almost looked pretty cool here despite the borderlands tier unfunny writing until it became yet an survival crafting game I really cant wait for this shitty mod to die'],
 ['Deep Grounded almost looked pretty cool even despite the borderlands fifth tier unfunny writing format until ultimately it became yet another survival crafting mobile game I really can t wait for this shitty trend starting to die'],
 ['Grounded almost was pretty cool even despite the top tier unfunny writing until we became yet another annoying crafting game I seriously cant wait on this shitty trend to die'],
 ['Appreciate the sonic concepts praxis Valenzuela and LandaPosas thread together in this talk multimodal listening soundwalks borderlands frameworks participatory action research and testimonios So many thoughtful and resonant intersections here'],
 ['Appreciate the sound concepts practices that Valenzuela and LandaPosas combine in this lecture multimodal listening soundwalks borderland frameworks participatory action research and testimonies So many thoughtful and resonant intersections here'],
 ['Evaluate the sound concepts concepts of Valensela and Landa Pozas together in this conversation multimodal listening walks border areas joint action studies etc So many amazing and resonant intersections here'],
 ['Appreciate the sonic concepts praxis Valenzuela and MorenoPosas have together in this talk multimodal listening soundwalks borderlands recordings participatory field research and testimonios So many thoughtful and resonant intersections here'],
 ['Appreciate by the sonic electronic concepts praxis Valenzuela and Landa Posas do thread together together in creating this talk multimodal visual listening digital soundwalks borderlands frameworks participatory action research interviews and testimonios So many thoughtful thoughts and resonant intersections reflected here'],
 ['Appreciate the sonic conversations actions Klein and LandaPosas brought together in our talk multimodal experiences soundwalks ethical frameworks participatory action practices and testimonios So many provocative and resonant intersections today'],
 ['Borderlands how do I submit a complaint Your CEO isnt paying his staff their bonuses'],
 ['Borderlands how can I file a complaint Your CEO doesnt pay his employees their bonuses'],
 ['Borderlands how to file a complaint Your CEO doesnt pay his employees bonuses'],
 ['Borderlands how did I submit a complaint Your CEO isnt paying his competitors their bonuses'],
 ['Borderlands how do suppose I submit a complaint Your CEO isnain t even paying his entire staff their bonuses'],
 ['Now how do I submit any complaint Your CEO isnt offering his staff their bonuses'],
 ['All the Borderlands are fuckin trash'],
 ['All the Borderlands are damn rubbish'],
 ['All the borderlands are fucking thrash'],
 ['All the Borderlands shit fuckin trash'],
 ['35 All the Borderlands are fuckin trash'],
 ['All the Borderlands are fuckin stupid'],
 ['Finally played through borderlands 3 The actual game play is great Almost all guns feel fun and I never once felt like I needed to grind That story on the other hand All I will say Is that Im very much so looking forward to the eventual cutscene skip'],
 ['Finally played by Borderlands 3 The actual game is great Almost all weapons feel funny and I never felt like I had to grind On the other hand All I will say is that I am very much looking forward to the eventual sequence skip'],
 ['This story on the other hand All I will say is that Im looking forward to an occasional slip'],
 ['Finally played through borderlands 3 The open game play is great Almost all guns feel fun and I never once felt like I needed to grind The story on to another hand All I will say Is that Im very much so looking forward to its eventual cutscene skip'],
 ['Finally played through borderlands 3 The actual game I play is great Almost all guns feel fun and yet I never once felt much like someone I seriously needed to grind That pretty story on the other side hand All I will say Is that Im very damn much so forward looking forward to the eventual endless cutscene skip'],
 ['Finally played through borderlands 5 The actual game play is great Almost all guns were fun and I never once felt sure I needed to grind That story is the other hand but I will say now oh yesm very much so looking forward to the extended cutscene skip'],
 ['Loving these new GhostLifestyle cans Anyone else drink Ghost'],
 ['I love these new GhostLifestyle cans Everyone else drinks ghost'],
 ['Love these new GhostLive cans Does anyone else drink Ghost'],
 ['Loving these new GhostLifestyle cans Anyone else drink Ghost'],
 ['Loving back these three new GhostLifestyle cans By Anyone else else drink Ghost'],
 ['do these new GhostLifestyleunk They want drink Ghost'],
 ['Come meet one of the lovely Gaming Goddesses'],
 ['Meet one of the lovely gambling goddesses'],
 ['Come meet one of the beautiful gods of gambling'],
 ['Come to one of the lovely Gaming Goddesses'],
 ['16 Come meet one of the lovely Gaming Goddesses'],
 ['Come meet one of the lovely Green Goddesses'],
 ['How the hell are we into Halloween month already'],
 ['How the hell are we already into Halloween month'],
 ['How the hell are we already in Halloween month'],
 ['How the hell are March into Halloween month already'],
 ['How the hell are pulling we into Halloween month starting already'],
 ['in the hell are we into Halloween month already'],
 ['What a bitch'],
 ['What a slut'],
 ['What a bitch'],
 ['What terrible bitch'],
 ['What a bitch'],
 ['What a miracle'],
 ['Ok I am LOVING THIS also playing Bombs Over Baghdad in anything gets me hype Very Borderlands like and the concept is A1'],
 ['Ok Im LOVING THIS also playing Bombs Over Baghdad in something gives me a hype Very Borderlands like and the concept is A1'],
 ['Ok I am LOVING THIS also playing Bombs Over Baghad in anything gets me here Very Borderlands like and the concept is A1'],
 ['Ok I am LOVING THIS also seeing Take Over Baghdad in anything gets me hype Very Borderlands like and the concept is awesome'],
 ['Ok sir I am LOVING THIS also just playing Bombs Over Baghdad and in case anything gets its me hype I Very Borderlands like and the concept is A1'],
 ['Ok I am LOVING THIS also playing Bombs and Earth in anything gets me hype Very good RPG and the concept is A1'],
 ['Just uninstalled all of my other games to make space for Borderlands 3'],
 ['Just uninstall all my other games to make room for Borderlands 3'],
 ['Just deleted all my other games to make room for Borderlands 3'],
 ['Just uninstalled all of my other games will make space for Borderlands 3'],
 ['Just uninstalled all other of my my other games to make space for watching Borderlands 3'],
 ['Just uninstalled all of all other games in make space for Borderlands 3'],
 ['Already loving Bleeding Edge what a clever game Cross between Overwatch Borderlands and Domination game mode Cool as'],
 ['I love Bleeding Edge what a clever game Crossroads of Overwatch Borderlands and Domination game mode Cool as'],
 ['Cross between Overwatch Borderlands and Domination game mode Cool as'],
 ['Already loving Bleeding Edge what a fun game Cross between Overwatch Borderlands and Xbox game mode Cool as'],
 ['Already also loving the Bleeding Edge what is a clever game Cross between Overwatch Borderlands and Future Domination game mode 2016 Cool out as'],
 ['Already played Bleeding Edge what a clever game Cross between fantasy Borderlands non Domination game mode Playing as'],

In [16]:
stopwords=stopwords.words('english')
stopwords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [17]:
filterd_txt=[]
for txt in tokens:
  for word in txt:
    if word not in stopwords:
      filterd_txt.append(word)
filterd_txt

['I am coming to the borders and I will kill you all',
 'im getting on borderlands and i will kill you all',
 'im coming on borderlands and i will murder you all',
 'im getting on borderlands 2 and i will murder you me all',
 'im getting into borderlands and i can murder you all',
 'So I spent a few hours making something for fun If you dont know I am a HUGE Borderlands fan and Maya is one of my favorite characters So I decided to make myself a wallpaper for my PC Here is the original image versus the creation I made Enjoy pictwittercommLsI5wf9Jg',
 'So I spent a couple of hours doing something for fun If you dont know that Im a huge Borderlands fan and Maya is one of my favorite characters I decided to make a wallpaper for my PC Heres the original picture compared to the creation I made Have fun pictwittercom mLsI5wf9Jg',
 'So I spent a few hours doing something for fun If you dont know Im a HUGE Borderlands fan and Maya is one of my favorite characters',
 'So I spent a few hours making something for fun If you dont know I am a HUGE RhandlerR fan and Maya is one of my favorite characters So I decided to make myself a wallpaper for my PC Here is the original image versus the creation I made Enjoy pictwittercommLsI5wf9Jg',
 '2010 So I spent a few hours making something for fun If you dont know I am a HUGE RhandlerR fan and Maya is one of my favorite characters So I decided to make myself a wallpaper for my PC Here is the original image versus the creation I made Enjoy pictwittercommLsI5wf9Jg',
 'RockHard La Varlope RARE POWERFUL HANDSOME JACKPOT Borderlands 3 Xbox dlvritRMTrgF',
 'RockHard La Varlope RARE POWERFUL HANDSOME JACKPOT Borderlands 3 Xbox dlvrit RMTrgF',
 'RockHard La Varlope RARE POWERFUL HANDSOME JACKPOT Borderlands 3 Xbox dfrit RMTrgF',
 'RockHard La Vita RARE BUT POWERFUL HANDSOME JACKPOT Borderlands 1 Xbox dlvritRMTrgF',
 'Live Rock Hard music La la Varlope RARE the POWERFUL Live HANDSOME i JACKPOT Borderlands 3 Sega Xbox dlvr From it e RMTrgF',
 'IHard like me RARE LONDON DE HANDSOME 2011 Borderlands 3 Xbox dlvritRMTrgF',
 'that was the first borderlands session in a long time where i actually had a really satisfying combat experience i got some really good kills',
 'this was the first Borderlands session in a long time where i actually had a really satisfying fighting experience i got some really good kills',
 'that was the first borderlands session in a long time where i actually had a really satisfying combat experience i got some really good kills',
 'that was the first borderlands session in a long time where i actually enjoyed a really satisfying combat experience i got some rather good kills',
 'that I was the first real borderlands session in a nice long wait time where i actually had a really satisfying combat experience and i got some really good kills',
 'that was the first borderlands session in a hot row where i actually had a really bad combat experience i did some really good kills',
 'the biggest dissappoinment in my life came out a year ago fuck borderlands 3',
 'The biggest disappointment of my life came a year ago',
 'The biggest disappointment of my life came a year ago',
 'the biggest dissappoinment in my life coming out a year ago fuck borderlands 3',
 'For the biggest male dissappoinment in my life came hanging out a year time ago fuck borderlands 3',
 'the biggest dissappoinment in my life came back last year ago fuck borderlands last',
 'WE FINISHED BORDERLANDS 3 FINALLY YAS Thank you for hanging out everyone It was fun I will try to stream tomorrow but if not I might so some IRL streams while awayu We shall see Thank you so much for the raids mompou_mumpow MegaMagwitch and KfdMitch',
 'WE FINALLY FINALLY FIND BORDERLANDS 3 YES Thank you all for hanging out It was fun Ill try to stream tomorrow but if not maybe some IRL streams Well see Thanks for the raids mompou _ mumpow MegaMagwitch and KfdMitch',
 'Thank you for hanging up everyone It was fun Ill try to get a haircut tomorrow but if it wasnt for me some IRL streams would still be in Hawaii Well see Thank you so much for the mompou _ mumpow MegaMagwife and fendMitch raids',
 'WE FINISHED BORDERLANDS 3 UPDATE YAS Thank you for hanging out guys It was fun I will try to stream and even if not I might so some IRL streams while awayu We shall go Thank you so much for the raids mompou_mumpow MegaMagwitch and Hope',
 'WE FINISHED BORDERLANDS 3 AND FINALLY YAS Thank you everyone for hanging out everyone It was fun I will try to make stream tomorrow but if not I might make so some IRL streams while awayu 10 We never shall see Thank you both so much for the raids mompou_mumpow or MegaMagwitch and 4 KfdMitch',
 'WE FINISHED BORDERLANDS 3 FINALLY YAS Hey you for hanging out so It was fun I will try that stream tomorrow and if not I might use some IRL streams from awayu We shall see Thank you so much how many raids mompou_mumpow did and their',
 'Man Gearbox really needs to fix this dissapointing drops in the new Borderlands 3 DLC cant be fine to farm bosses on Mayhem 10 to get 1 legendary drop while anywhere else i get 610 drops Really sucks alot',
 'Man Gearbox really needs to fix these disappointing drops in the new Borderlands 3 DLC for farm bosses on Mayhem 10 to get a legendary drop while I get 610 drops elsewhere',
 'Man Gearbox really needs to fix this disssapointing drops in the new Borderlands 3 DLC cant be fine to farm bosses on Mayhem 10 to get 1 legendary drop while elsewhere i get 610 drops Really sucks alot',
 'Man Bethesda really needs to fix this dissapointing drops and the new Borderlands 3 It cant be fine to farm bosses on Mayhem 10 to get 1 legendary drop while anywhere else i get 610 drops Really sucks',
 'Man Gearbox really needs to fix this dissapointing drops in the completely new Borderlands 3 Days DLC i cant e be fine having to be farm bosses on Mayhem 10 to e get 1 legendary foot drop while anywhere else i get 6 10 drops It Really sucks to alot',
 'unk Gearbox really time to fix this 10 drops in the new Borderlands 3 DLC or be fine to force bosses on Mayhem 10 to get a legendary drop while everyone else i get 610 drops Really needs alot',
 'Check out this epic streamer',
 'Check out this epic streamer',
 'Watch this epic striptease',
 'Check out our epic streamer',
 'Check out this big epic streamer',
 'Checkunk this epic streamer',
 'Blaming Sight for Tardiness A little bit of borderlands I got called in early for work tomorrow so I cant make up time Sorry my loves twitchtvpunnisenpai',
 'A bit of borderland I was called to work tomorrow morning so I cant catch up Sorry my love twitchtv punnisenpai',
 'Guilty of sobriety A bit of a borderline I was called to work early tomorrow so I cant catch up',
 'Blaming Sight for Tardiness A little bit of borderlands I got called in early for work tomorrow so I cant make up time Sorry my loves twitchtvpunnisenpai',
 'for Blaming Sight for Tardiness A little bit of borderlands I got called in early for work tomorrow so I cant make up time Sorry my loves twitchtvpunnisenpai',
 'why does like every man in borderlands have slicked back hair havent you heard of bangs you stupid assholes',
 'Why like every man in border countries have you not heard of bangs you stupid assholes',
 'Why like everyone else in the border countries have your hair fallen off have you not heard that you are stupid aliens',
 'why does likeunk man in borderlands have slicked back hair or you heard of bangs you stupid assholes',
 'why Beth does like every man in borderlands have she slicked that back hair haven t you heard enough of gray bangs you stupid assholes',
 'why does practically every man in France have slicked back hair havent you heard of bangs the greedy assholes',
 '45',
 'Going to finish up Borderlands 2 today Ive got some new commands set up and am looking forward to a good stream Starting in about am hour',
 'I will finish Borderlands 2 today I have some new commands set up and am looking forward to a good stream Start in about an hour',
 'Im going to finish Borderlands 2 today I have some new commands installed and Im looking forward to a good stream',
 'Going to finish up Borderlands 2 today Ive got some new events set up and am look forward to a good stream Starting in about 20 hour',
 'Going to finish finish cleaning up Borderlands 2 today Ive just got her some new commands set all up and am looking forward it to a good stream Starting in about am hour',
 'Going to finish up volume 2 today Ive got some awesome server set up and is looking forward to a good stream Starting in about am hour',
 'imma probably play some borderlands tps in a bit thatll be fun',
 'imma is probably playing a bit of borderland tps That will be fun',
 'imma will probably play some border tps in a bit Its going to be fun',
 'imma probably play live borderlands tps in a bit thatll be fun',
 'for imma probably play some borderlands tps in a bit thatyer ll be a fun',
 'imma probably got some video tps in a bit thatll make fun',
 'One of our own ProfZeroo is live w borderlands 3 Catch him here buffly2WmmiP5 Say Streamer Shouts in chat for a chance to be in a coming streamer_shouts Shout Out',
 'One of our own ProfZeroo is live w borderlands 3 catch him here buffly 2WmmiP5 Say Streamer Shouts in chat for a chance to be in an upcoming one streamer _ shouts Shout Out',
 'One of our own ProfZero live w borderlands 3 Catch him here buffly 2WmmiP5 Say Stream Shouts in chat for a chat for a chance to be in a coming stream _ Shouts Shout Out',
 'One of our own ProfZeroo is live borderlands 3 Catch him here buffly2WmmiP5 p Say some Shouts in chat a chance to be in a coming Also Shout Out',
 'One of our shows own ProfZeroo is live via w at borderlands 3 and UNK Catch him here the buff ly to 2WmmiP5 to Say Streamer Shouts in chat for a chance to officially be in a series coming streamer_shouts 1 Shout Out',
 'One of its own movies is live w ProfZeroo 3 Catch him from buffly2WmmiP5 for Streamer Shouts in invitation or a chance to be out a coming All 3 invites',
 'FUCK YESSSSSSSS',
 'FICK YESSSSSS',
 'FUCK YESSSSSSSS',
 'FUCK YESSSSSSSSunk',
 'A FUCK YESSSSSSSS',
 'FUCK YOU',
 'I hate that this easy mayhem modifier event on mayhem wont last forever this is the most fun ive had in the game since they added them horrible modifiers Borderlands please give me the option to play mayhem 10 but turn the modifiers off PLS',
 'I hate that this simple Chaos Modifier event on Chaos wont last forever Thats the most fun Ive had in the game since they added terrible modifiers Borderlands please give me the option to play Chaos 10 but turn off the modifiers',
 'I hate that this easy mayhem modifier event on mayhem wont last forever this is the most fun ive had in the game since they added them horrible modifiers Borderlands please give me the option to play mayhem 10 but turn the modifiers off PLS',
 'I hate saying this easy day 9 event on mayhem wont last forever this is the most fun ive had in the game since they added them horrible modifiers Borderlands please give me some ability to play mayhem 10 but turn the modifiers off PLS',
 'I hate thinking that this easy mayhem modifier event on total mayhem won t last forever this is the absolutely most ridiculous fun experience i ve had in the game almost since they added them horrible modifiers Borderlands please do give me the option option to a play mayhem 10 but turn the modifiers off PLS',
 'I hate that this easy horrible modifier event on game 10 last forever That is the best fun ive taken in the past until they added them horrible modifiers Borderlands please send me the option to play mayhem 10 but turn the modifiers for PLS',
 'Grounded almost looked pretty cool even despite the borderlands tier unfunny writing until it became yet another survival crafting game I really cant wait for this shitty trend to die',
 'Grounded looked cool despite the borderline unfunny writing until it became another survival crafting game I really cant wait for this crappy trend to die',
 'Grosskreutz looked pretty cool even despite the unfunny spelling until it turned into another survival game I really cant wait for this crap trend to die',
 'Grounded almost looked pretty cool here despite the borderlands tier unfunny writing until it became yet an survival crafting game I really cant wait for this shitty mod to die',
 'Deep Grounded almost looked pretty cool even despite the borderlands fifth tier unfunny writing format until ultimately it became yet another survival crafting mobile game I really can t wait for this shitty trend starting to die',
 'Grounded almost was pretty cool even despite the top tier unfunny writing until we became yet another annoying crafting game I seriously cant wait on this shitty trend to die',
 'Appreciate the sonic concepts praxis Valenzuela and LandaPosas thread together in this talk multimodal listening soundwalks borderlands frameworks participatory action research and testimonios So many thoughtful and resonant intersections here',
 'Appreciate the sound concepts practices that Valenzuela and LandaPosas combine in this lecture multimodal listening soundwalks borderland frameworks participatory action research and testimonies So many thoughtful and resonant intersections here',
 'Evaluate the sound concepts concepts of Valensela and Landa Pozas together in this conversation multimodal listening walks border areas joint action studies etc So many amazing and resonant intersections here',
 'Appreciate the sonic concepts praxis Valenzuela and MorenoPosas have together in this talk multimodal listening soundwalks borderlands recordings participatory field research and testimonios So many thoughtful and resonant intersections here',
 'Appreciate by the sonic electronic concepts praxis Valenzuela and Landa Posas do thread together together in creating this talk multimodal visual listening digital soundwalks borderlands frameworks participatory action research interviews and testimonios So many thoughtful thoughts and resonant intersections reflected here',
 'Appreciate the sonic conversations actions Klein and LandaPosas brought together in our talk multimodal experiences soundwalks ethical frameworks participatory action practices and testimonios So many provocative and resonant intersections today',
 'Borderlands how do I submit a complaint Your CEO isnt paying his staff their bonuses',
 'Borderlands how can I file a complaint Your CEO doesnt pay his employees their bonuses',
 'Borderlands how to file a complaint Your CEO doesnt pay his employees bonuses',
 'Borderlands how did I submit a complaint Your CEO isnt paying his competitors their bonuses',
 'Borderlands how do suppose I submit a complaint Your CEO isnain t even paying his entire staff their bonuses',
 'Now how do I submit any complaint Your CEO isnt offering his staff their bonuses',
 'All the Borderlands are fuckin trash',
 'All the Borderlands are damn rubbish',
 'All the borderlands are fucking thrash',
 'All the Borderlands shit fuckin trash',
 '35 All the Borderlands are fuckin trash',
 'All the Borderlands are fuckin stupid',
 'Finally played through borderlands 3 The actual game play is great Almost all guns feel fun and I never once felt like I needed to grind That story on the other hand All I will say Is that Im very much so looking forward to the eventual cutscene skip',
 'Finally played by Borderlands 3 The actual game is great Almost all weapons feel funny and I never felt like I had to grind On the other hand All I will say is that I am very much looking forward to the eventual sequence skip',
 'This story on the other hand All I will say is that Im looking forward to an occasional slip',
 'Finally played through borderlands 3 The open game play is great Almost all guns feel fun and I never once felt like I needed to grind The story on to another hand All I will say Is that Im very much so looking forward to its eventual cutscene skip',
 'Finally played through borderlands 3 The actual game I play is great Almost all guns feel fun and yet I never once felt much like someone I seriously needed to grind That pretty story on the other side hand All I will say Is that Im very damn much so forward looking forward to the eventual endless cutscene skip',
 'Finally played through borderlands 5 The actual game play is great Almost all guns were fun and I never once felt sure I needed to grind That story is the other hand but I will say now oh yesm very much so looking forward to the extended cutscene skip',
 'Loving these new GhostLifestyle cans Anyone else drink Ghost',
 'I love these new GhostLifestyle cans Everyone else drinks ghost',
 'Love these new GhostLive cans Does anyone else drink Ghost',
 'Loving these new GhostLifestyle cans Anyone else drink Ghost',
 'Loving back these three new GhostLifestyle cans By Anyone else else drink Ghost',
 'do these new GhostLifestyleunk They want drink Ghost',
 'Come meet one of the lovely Gaming Goddesses',
 'Meet one of the lovely gambling goddesses',
 'Come meet one of the beautiful gods of gambling',
 'Come to one of the lovely Gaming Goddesses',
 '16 Come meet one of the lovely Gaming Goddesses',
 'Come meet one of the lovely Green Goddesses',
 'How the hell are we into Halloween month already',
 'How the hell are we already into Halloween month',
 'How the hell are we already in Halloween month',
 'How the hell are March into Halloween month already',
 'How the hell are pulling we into Halloween month starting already',
 'in the hell are we into Halloween month already',
 'What a bitch',
 'What a slut',
 'What a bitch',
 'What terrible bitch',
 'What a bitch',
 'What a miracle',
 'Ok I am LOVING THIS also playing Bombs Over Baghdad in anything gets me hype Very Borderlands like and the concept is A1',
 'Ok Im LOVING THIS also playing Bombs Over Baghdad in something gives me a hype Very Borderlands like and the concept is A1',
 'Ok I am LOVING THIS also playing Bombs Over Baghad in anything gets me here Very Borderlands like and the concept is A1',
 'Ok I am LOVING THIS also seeing Take Over Baghdad in anything gets me hype Very Borderlands like and the concept is awesome',
 'Ok sir I am LOVING THIS also just playing Bombs Over Baghdad and in case anything gets its me hype I Very Borderlands like and the concept is A1',
 'Ok I am LOVING THIS also playing Bombs and Earth in anything gets me hype Very good RPG and the concept is A1',
 'Just uninstalled all of my other games to make space for Borderlands 3',
 'Just uninstall all my other games to make room for Borderlands 3',
 'Just deleted all my other games to make room for Borderlands 3',
 'Just uninstalled all of my other games will make space for Borderlands 3',
 'Just uninstalled all other of my my other games to make space for watching Borderlands 3',
 'Just uninstalled all of all other games in make space for Borderlands 3',
 'Already loving Bleeding Edge what a clever game Cross between Overwatch Borderlands and Domination game mode Cool as',
 'I love Bleeding Edge what a clever game Crossroads of Overwatch Borderlands and Domination game mode Cool as',
 'Cross between Overwatch Borderlands and Domination game mode Cool as',
 'Already loving Bleeding Edge what a fun game Cross between Overwatch Borderlands and Xbox game mode Cool as',
 'Already also loving the Bleeding Edge what is a clever game Cross between Overwatch Borderlands and Future Domination game mode 2016 Cool out as',
 'Already played Bleeding Edge what a clever game Cross between fantasy Borderlands non Domination game mode Playing as',
 'Bioshock AND borderlands coming to the switch bitch count me the fuck in',
 'Bioshock AND borderlands coming to the switch bitch count me the fuck in',
 'Bioshock And borderlands coming to the switch bitch count me the fuck in',
 'Bioshock AND borderlands coming to the desert bitch count me the fuck in',
 'Bioshock Montana AND other borderlands Are coming to the switch bitch count me the fuck in',

In [18]:
#stemming
stm=PorterStemmer()
stemmed=[]
for word in filterd_txt:
  stemmed.append(stm.stem(word))
stemmed

['i am coming to the borders and i will kill you al',
 'im getting on borderlands and i will kill you al',
 'im coming on borderlands and i will murder you al',
 'im getting on borderlands 2 and i will murder you me al',
 'im getting into borderlands and i can murder you al',
 'so i spent a few hours making something for fun if you dont know i am a huge borderlands fan and maya is one of my favorite characters so i decided to make myself a wallpaper for my pc here is the original image versus the creation i made enjoy pictwittercommlsi5wf9jg',
 'so i spent a couple of hours doing something for fun if you dont know that im a huge borderlands fan and maya is one of my favorite characters i decided to make a wallpaper for my pc heres the original picture compared to the creation i made have fun pictwittercom mlsi5wf9jg',
 'so i spent a few hours doing something for fun if you dont know im a huge borderlands fan and maya is one of my favorite charact',
 'so i spent a few hours making something for fun if you dont know i am a huge rhandlerr fan and maya is one of my favorite characters so i decided to make myself a wallpaper for my pc here is the original image versus the creation i made enjoy pictwittercommlsi5wf9jg',
 '2010 so i spent a few hours making something for fun if you dont know i am a huge rhandlerr fan and maya is one of my favorite characters so i decided to make myself a wallpaper for my pc here is the original image versus the creation i made enjoy pictwittercommlsi5wf9jg',
 'rockhard la varlope rare powerful handsome jackpot borderlands 3 xbox dlvritrmtrgf',
 'rockhard la varlope rare powerful handsome jackpot borderlands 3 xbox dlvrit rmtrgf',
 'rockhard la varlope rare powerful handsome jackpot borderlands 3 xbox dfrit rmtrgf',
 'rockhard la vita rare but powerful handsome jackpot borderlands 1 xbox dlvritrmtrgf',
 'live rock hard music la la varlope rare the powerful live handsome i jackpot borderlands 3 sega xbox dlvr from it e rmtrgf',
 'ihard like me rare london de handsome 2011 borderlands 3 xbox dlvritrmtrgf',
 'that was the first borderlands session in a long time where i actually had a really satisfying combat experience i got some really good kil',
 'this was the first borderlands session in a long time where i actually had a really satisfying fighting experience i got some really good kil',
 'that was the first borderlands session in a long time where i actually had a really satisfying combat experience i got some really good kil',
 'that was the first borderlands session in a long time where i actually enjoyed a really satisfying combat experience i got some rather good kil',
 'that i was the first real borderlands session in a nice long wait time where i actually had a really satisfying combat experience and i got some really good kil',
 'that was the first borderlands session in a hot row where i actually had a really bad combat experience i did some really good kil',
 'the biggest dissappoinment in my life came out a year ago fuck borderlands 3',
 'the biggest disappointment of my life came a year ago',
 'the biggest disappointment of my life came a year ago',
 'the biggest dissappoinment in my life coming out a year ago fuck borderlands 3',
 'for the biggest male dissappoinment in my life came hanging out a year time ago fuck borderlands 3',
 'the biggest dissappoinment in my life came back last year ago fuck borderlands last',
 'we finished borderlands 3 finally yas thank you for hanging out everyone it was fun i will try to stream tomorrow but if not i might so some irl streams while awayu we shall see thank you so much for the raids mompou_mumpow megamagwitch and kfdmitch',
 'we finally finally find borderlands 3 yes thank you all for hanging out it was fun ill try to stream tomorrow but if not maybe some irl streams well see thanks for the raids mompou _ mumpow megamagwitch and kfdmitch',
 'thank you for hanging up everyone it was fun ill try to get a haircut tomorrow but if it wasnt for me some irl streams would still be in hawaii well see thank you so much for the mompou _ mumpow megamagwife and fendmitch raid',
 'we finished borderlands 3 update yas thank you for hanging out guys it was fun i will try to stream and even if not i might so some irl streams while awayu we shall go thank you so much for the raids mompou_mumpow megamagwitch and hop',
 'we finished borderlands 3 and finally yas thank you everyone for hanging out everyone it was fun i will try to make stream tomorrow but if not i might make so some irl streams while awayu 10 we never shall see thank you both so much for the raids mompou_mumpow or megamagwitch and 4 kfdmitch',
 'we finished borderlands 3 finally yas hey you for hanging out so it was fun i will try that stream tomorrow and if not i might use some irl streams from awayu we shall see thank you so much how many raids mompou_mumpow did and their',
 'man gearbox really needs to fix this dissapointing drops in the new borderlands 3 dlc cant be fine to farm bosses on mayhem 10 to get 1 legendary drop while anywhere else i get 610 drops really sucks alot',
 'man gearbox really needs to fix these disappointing drops in the new borderlands 3 dlc for farm bosses on mayhem 10 to get a legendary drop while i get 610 drops elsewher',
 'man gearbox really needs to fix this disssapointing drops in the new borderlands 3 dlc cant be fine to farm bosses on mayhem 10 to get 1 legendary drop while elsewhere i get 610 drops really sucks alot',
 'man bethesda really needs to fix this dissapointing drops and the new borderlands 3 it cant be fine to farm bosses on mayhem 10 to get 1 legendary drop while anywhere else i get 610 drops really suck',
 'man gearbox really needs to fix this dissapointing drops in the completely new borderlands 3 days dlc i cant e be fine having to be farm bosses on mayhem 10 to e get 1 legendary foot drop while anywhere else i get 6 10 drops it really sucks to alot',
 'unk gearbox really time to fix this 10 drops in the new borderlands 3 dlc or be fine to force bosses on mayhem 10 to get a legendary drop while everyone else i get 610 drops really needs alot',
 'check out this epic stream',
 'check out this epic stream',
 'watch this epic stripteas',
 'check out our epic stream',
 'check out this big epic stream',
 'checkunk this epic stream',
 'blaming sight for tardiness a little bit of borderlands i got called in early for work tomorrow so i cant make up time sorry my loves twitchtvpunnisenpai',
 'a bit of borderland i was called to work tomorrow morning so i cant catch up sorry my love twitchtv punnisenpai',
 'guilty of sobriety a bit of a borderline i was called to work early tomorrow so i cant catch up',
 'blaming sight for tardiness a little bit of borderlands i got called in early for work tomorrow so i cant make up time sorry my loves twitchtvpunnisenpai',
 'for blaming sight for tardiness a little bit of borderlands i got called in early for work tomorrow so i cant make up time sorry my loves twitchtvpunnisenpai',
 'why does like every man in borderlands have slicked back hair havent you heard of bangs you stupid asshol',
 'why like every man in border countries have you not heard of bangs you stupid asshol',
 'why like everyone else in the border countries have your hair fallen off have you not heard that you are stupid alien',
 'why does likeunk man in borderlands have slicked back hair or you heard of bangs you stupid asshol',
 'why beth does like every man in borderlands have she slicked that back hair haven t you heard enough of gray bangs you stupid asshol',
 'why does practically every man in france have slicked back hair havent you heard of bangs the greedy asshol',
 '45',
 'going to finish up borderlands 2 today ive got some new commands set up and am looking forward to a good stream starting in about am hour',
 'i will finish borderlands 2 today i have some new commands set up and am looking forward to a good stream start in about an hour',
 'im going to finish borderlands 2 today i have some new commands installed and im looking forward to a good stream',
 'going to finish up borderlands 2 today ive got some new events set up and am look forward to a good stream starting in about 20 hour',
 'going to finish finish cleaning up borderlands 2 today ive just got her some new commands set all up and am looking forward it to a good stream starting in about am hour',
 'going to finish up volume 2 today ive got some awesome server set up and is looking forward to a good stream starting in about am hour',
 'imma probably play some borderlands tps in a bit thatll be fun',
 'imma is probably playing a bit of borderland tps that will be fun',
 'imma will probably play some border tps in a bit its going to be fun',
 'imma probably play live borderlands tps in a bit thatll be fun',
 'for imma probably play some borderlands tps in a bit thatyer ll be a fun',
 'imma probably got some video tps in a bit thatll make fun',
 'one of our own profzeroo is live w borderlands 3 catch him here buffly2wmmip5 say streamer shouts in chat for a chance to be in a coming streamer_shouts shout out',
 'one of our own profzeroo is live w borderlands 3 catch him here buffly 2wmmip5 say streamer shouts in chat for a chance to be in an upcoming one streamer _ shouts shout out',
 'one of our own profzero live w borderlands 3 catch him here buffly 2wmmip5 say stream shouts in chat for a chat for a chance to be in a coming stream _ shouts shout out',
 'one of our own profzeroo is live borderlands 3 catch him here buffly2wmmip5 p say some shouts in chat a chance to be in a coming also shout out',
 'one of our shows own profzeroo is live via w at borderlands 3 and unk catch him here the buff ly to 2wmmip5 to say streamer shouts in chat for a chance to officially be in a series coming streamer_shouts 1 shout out',
 'one of its own movies is live w profzeroo 3 catch him from buffly2wmmip5 for streamer shouts in invitation or a chance to be out a coming all 3 invit',
 'fuck yessssssss',
 'fick yessssss',
 'fuck yessssssss',
 'fuck yessssssssunk',
 'a fuck yessssssss',
 'fuck you',
 'i hate that this easy mayhem modifier event on mayhem wont last forever this is the most fun ive had in the game since they added them horrible modifiers borderlands please give me the option to play mayhem 10 but turn the modifiers off pl',
 'i hate that this simple chaos modifier event on chaos wont last forever thats the most fun ive had in the game since they added terrible modifiers borderlands please give me the option to play chaos 10 but turn off the modifi',
 'i hate that this easy mayhem modifier event on mayhem wont last forever this is the most fun ive had in the game since they added them horrible modifiers borderlands please give me the option to play mayhem 10 but turn the modifiers off pl',
 'i hate saying this easy day 9 event on mayhem wont last forever this is the most fun ive had in the game since they added them horrible modifiers borderlands please give me some ability to play mayhem 10 but turn the modifiers off pl',
 'i hate thinking that this easy mayhem modifier event on total mayhem won t last forever this is the absolutely most ridiculous fun experience i ve had in the game almost since they added them horrible modifiers borderlands please do give me the option option to a play mayhem 10 but turn the modifiers off pl',
 'i hate that this easy horrible modifier event on game 10 last forever that is the best fun ive taken in the past until they added them horrible modifiers borderlands please send me the option to play mayhem 10 but turn the modifiers for pl',
 'grounded almost looked pretty cool even despite the borderlands tier unfunny writing until it became yet another survival crafting game i really cant wait for this shitty trend to di',
 'grounded looked cool despite the borderline unfunny writing until it became another survival crafting game i really cant wait for this crappy trend to di',
 'grosskreutz looked pretty cool even despite the unfunny spelling until it turned into another survival game i really cant wait for this crap trend to di',
 'grounded almost looked pretty cool here despite the borderlands tier unfunny writing until it became yet an survival crafting game i really cant wait for this shitty mod to di',
 'deep grounded almost looked pretty cool even despite the borderlands fifth tier unfunny writing format until ultimately it became yet another survival crafting mobile game i really can t wait for this shitty trend starting to di',
 'grounded almost was pretty cool even despite the top tier unfunny writing until we became yet another annoying crafting game i seriously cant wait on this shitty trend to di',
 'appreciate the sonic concepts praxis valenzuela and landaposas thread together in this talk multimodal listening soundwalks borderlands frameworks participatory action research and testimonios so many thoughtful and resonant intersections her',
 'appreciate the sound concepts practices that valenzuela and landaposas combine in this lecture multimodal listening soundwalks borderland frameworks participatory action research and testimonies so many thoughtful and resonant intersections her',
 'evaluate the sound concepts concepts of valensela and landa pozas together in this conversation multimodal listening walks border areas joint action studies etc so many amazing and resonant intersections her',
 'appreciate the sonic concepts praxis valenzuela and morenoposas have together in this talk multimodal listening soundwalks borderlands recordings participatory field research and testimonios so many thoughtful and resonant intersections her',
 'appreciate by the sonic electronic concepts praxis valenzuela and landa posas do thread together together in creating this talk multimodal visual listening digital soundwalks borderlands frameworks participatory action research interviews and testimonios so many thoughtful thoughts and resonant intersections reflected her',
 'appreciate the sonic conversations actions klein and landaposas brought together in our talk multimodal experiences soundwalks ethical frameworks participatory action practices and testimonios so many provocative and resonant intersections today',
 'borderlands how do i submit a complaint your ceo isnt paying his staff their bonus',
 'borderlands how can i file a complaint your ceo doesnt pay his employees their bonus',
 'borderlands how to file a complaint your ceo doesnt pay his employees bonus',
 'borderlands how did i submit a complaint your ceo isnt paying his competitors their bonus',
 'borderlands how do suppose i submit a complaint your ceo isnain t even paying his entire staff their bonus',
 'now how do i submit any complaint your ceo isnt offering his staff their bonus',
 'all the borderlands are fuckin trash',
 'all the borderlands are damn rubbish',
 'all the borderlands are fucking thrash',
 'all the borderlands shit fuckin trash',
 '35 all the borderlands are fuckin trash',
 'all the borderlands are fuckin stupid',
 'finally played through borderlands 3 the actual game play is great almost all guns feel fun and i never once felt like i needed to grind that story on the other hand all i will say is that im very much so looking forward to the eventual cutscene skip',
 'finally played by borderlands 3 the actual game is great almost all weapons feel funny and i never felt like i had to grind on the other hand all i will say is that i am very much looking forward to the eventual sequence skip',
 'this story on the other hand all i will say is that im looking forward to an occasional slip',
 'finally played through borderlands 3 the open game play is great almost all guns feel fun and i never once felt like i needed to grind the story on to another hand all i will say is that im very much so looking forward to its eventual cutscene skip',
 'finally played through borderlands 3 the actual game i play is great almost all guns feel fun and yet i never once felt much like someone i seriously needed to grind that pretty story on the other side hand all i will say is that im very damn much so forward looking forward to the eventual endless cutscene skip',
 'finally played through borderlands 5 the actual game play is great almost all guns were fun and i never once felt sure i needed to grind that story is the other hand but i will say now oh yesm very much so looking forward to the extended cutscene skip',
 'loving these new ghostlifestyle cans anyone else drink ghost',
 'i love these new ghostlifestyle cans everyone else drinks ghost',
 'love these new ghostlive cans does anyone else drink ghost',
 'loving these new ghostlifestyle cans anyone else drink ghost',
 'loving back these three new ghostlifestyle cans by anyone else else drink ghost',
 'do these new ghostlifestyleunk they want drink ghost',
 'come meet one of the lovely gaming goddess',
 'meet one of the lovely gambling goddess',
 'come meet one of the beautiful gods of gambl',
 'come to one of the lovely gaming goddess',
 '16 come meet one of the lovely gaming goddess',
 'come meet one of the lovely green goddess',
 'how the hell are we into halloween month alreadi',
 'how the hell are we already into halloween month',
 'how the hell are we already in halloween month',
 'how the hell are march into halloween month alreadi',
 'how the hell are pulling we into halloween month starting alreadi',
 'in the hell are we into halloween month alreadi',
 'what a bitch',
 'what a slut',
 'what a bitch',
 'what terrible bitch',
 'what a bitch',
 'what a miracl',
 'ok i am loving this also playing bombs over baghdad in anything gets me hype very borderlands like and the concept is a1',
 'ok im loving this also playing bombs over baghdad in something gives me a hype very borderlands like and the concept is a1',
 'ok i am loving this also playing bombs over baghad in anything gets me here very borderlands like and the concept is a1',
 'ok i am loving this also seeing take over baghdad in anything gets me hype very borderlands like and the concept is awesom',
 'ok sir i am loving this also just playing bombs over baghdad and in case anything gets its me hype i very borderlands like and the concept is a1',
 'ok i am loving this also playing bombs and earth in anything gets me hype very good rpg and the concept is a1',
 'just uninstalled all of my other games to make space for borderlands 3',
 'just uninstall all my other games to make room for borderlands 3',
 'just deleted all my other games to make room for borderlands 3',
 'just uninstalled all of my other games will make space for borderlands 3',
 'just uninstalled all other of my my other games to make space for watching borderlands 3',
 'just uninstalled all of all other games in make space for borderlands 3',
 'already loving bleeding edge what a clever game cross between overwatch borderlands and domination game mode cool a',
 'i love bleeding edge what a clever game crossroads of overwatch borderlands and domination game mode cool a',
 'cross between overwatch borderlands and domination game mode cool a',
 'already loving bleeding edge what a fun game cross between overwatch borderlands and xbox game mode cool a',
 'already also loving the bleeding edge what is a clever game cross between overwatch borderlands and future domination game mode 2016 cool out a',
 'already played bleeding edge what a clever game cross between fantasy borderlands non domination game mode playing a',
 'bioshock and borderlands coming to the switch bitch count me the fuck in',
 'bioshock and borderlands coming to the switch bitch count me the fuck in',
 'bioshock and borderlands coming to the switch bitch count me the fuck in',
 'bioshock and borderlands coming to the desert bitch count me the fuck in',
 'bioshock montana and other borderlands are coming to the switch bitch count me the fuck in',
 'bioshock and borderlands coming after your switch bitch count me the fuck in',

In [19]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\divya\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\divya\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from scikit-learn) (2.2.2)
Requirement already satisfied: scipy>=1.6.0 in c:\users\divya\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from scikit-learn) (1.15.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\divya\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\divya\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:

import sklearn
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer()
stem_ = [''.join(text) for text in stemmed]
stem_

['i am coming to the borders and i will kill you al',
 'im getting on borderlands and i will kill you al',
 'im coming on borderlands and i will murder you al',
 'im getting on borderlands 2 and i will murder you me al',
 'im getting into borderlands and i can murder you al',
 'so i spent a few hours making something for fun if you dont know i am a huge borderlands fan and maya is one of my favorite characters so i decided to make myself a wallpaper for my pc here is the original image versus the creation i made enjoy pictwittercommlsi5wf9jg',
 'so i spent a couple of hours doing something for fun if you dont know that im a huge borderlands fan and maya is one of my favorite characters i decided to make a wallpaper for my pc heres the original picture compared to the creation i made have fun pictwittercom mlsi5wf9jg',
 'so i spent a few hours doing something for fun if you dont know im a huge borderlands fan and maya is one of my favorite charact',
 'so i spent a few hours making something for fun if you dont know i am a huge rhandlerr fan and maya is one of my favorite characters so i decided to make myself a wallpaper for my pc here is the original image versus the creation i made enjoy pictwittercommlsi5wf9jg',
 '2010 so i spent a few hours making something for fun if you dont know i am a huge rhandlerr fan and maya is one of my favorite characters so i decided to make myself a wallpaper for my pc here is the original image versus the creation i made enjoy pictwittercommlsi5wf9jg',
 'rockhard la varlope rare powerful handsome jackpot borderlands 3 xbox dlvritrmtrgf',
 'rockhard la varlope rare powerful handsome jackpot borderlands 3 xbox dlvrit rmtrgf',
 'rockhard la varlope rare powerful handsome jackpot borderlands 3 xbox dfrit rmtrgf',
 'rockhard la vita rare but powerful handsome jackpot borderlands 1 xbox dlvritrmtrgf',
 'live rock hard music la la varlope rare the powerful live handsome i jackpot borderlands 3 sega xbox dlvr from it e rmtrgf',
 'ihard like me rare london de handsome 2011 borderlands 3 xbox dlvritrmtrgf',
 'that was the first borderlands session in a long time where i actually had a really satisfying combat experience i got some really good kil',
 'this was the first borderlands session in a long time where i actually had a really satisfying fighting experience i got some really good kil',
 'that was the first borderlands session in a long time where i actually had a really satisfying combat experience i got some really good kil',
 'that was the first borderlands session in a long time where i actually enjoyed a really satisfying combat experience i got some rather good kil',
 'that i was the first real borderlands session in a nice long wait time where i actually had a really satisfying combat experience and i got some really good kil',
 'that was the first borderlands session in a hot row where i actually had a really bad combat experience i did some really good kil',
 'the biggest dissappoinment in my life came out a year ago fuck borderlands 3',
 'the biggest disappointment of my life came a year ago',
 'the biggest disappointment of my life came a year ago',
 'the biggest dissappoinment in my life coming out a year ago fuck borderlands 3',
 'for the biggest male dissappoinment in my life came hanging out a year time ago fuck borderlands 3',
 'the biggest dissappoinment in my life came back last year ago fuck borderlands last',
 'we finished borderlands 3 finally yas thank you for hanging out everyone it was fun i will try to stream tomorrow but if not i might so some irl streams while awayu we shall see thank you so much for the raids mompou_mumpow megamagwitch and kfdmitch',
 'we finally finally find borderlands 3 yes thank you all for hanging out it was fun ill try to stream tomorrow but if not maybe some irl streams well see thanks for the raids mompou _ mumpow megamagwitch and kfdmitch',
 'thank you for hanging up everyone it was fun ill try to get a haircut tomorrow but if it wasnt for me some irl streams would still be in hawaii well see thank you so much for the mompou _ mumpow megamagwife and fendmitch raid',
 'we finished borderlands 3 update yas thank you for hanging out guys it was fun i will try to stream and even if not i might so some irl streams while awayu we shall go thank you so much for the raids mompou_mumpow megamagwitch and hop',
 'we finished borderlands 3 and finally yas thank you everyone for hanging out everyone it was fun i will try to make stream tomorrow but if not i might make so some irl streams while awayu 10 we never shall see thank you both so much for the raids mompou_mumpow or megamagwitch and 4 kfdmitch',
 'we finished borderlands 3 finally yas hey you for hanging out so it was fun i will try that stream tomorrow and if not i might use some irl streams from awayu we shall see thank you so much how many raids mompou_mumpow did and their',
 'man gearbox really needs to fix this dissapointing drops in the new borderlands 3 dlc cant be fine to farm bosses on mayhem 10 to get 1 legendary drop while anywhere else i get 610 drops really sucks alot',
 'man gearbox really needs to fix these disappointing drops in the new borderlands 3 dlc for farm bosses on mayhem 10 to get a legendary drop while i get 610 drops elsewher',
 'man gearbox really needs to fix this disssapointing drops in the new borderlands 3 dlc cant be fine to farm bosses on mayhem 10 to get 1 legendary drop while elsewhere i get 610 drops really sucks alot',
 'man bethesda really needs to fix this dissapointing drops and the new borderlands 3 it cant be fine to farm bosses on mayhem 10 to get 1 legendary drop while anywhere else i get 610 drops really suck',
 'man gearbox really needs to fix this dissapointing drops in the completely new borderlands 3 days dlc i cant e be fine having to be farm bosses on mayhem 10 to e get 1 legendary foot drop while anywhere else i get 6 10 drops it really sucks to alot',
 'unk gearbox really time to fix this 10 drops in the new borderlands 3 dlc or be fine to force bosses on mayhem 10 to get a legendary drop while everyone else i get 610 drops really needs alot',
 'check out this epic stream',
 'check out this epic stream',
 'watch this epic stripteas',
 'check out our epic stream',
 'check out this big epic stream',
 'checkunk this epic stream',
 'blaming sight for tardiness a little bit of borderlands i got called in early for work tomorrow so i cant make up time sorry my loves twitchtvpunnisenpai',
 'a bit of borderland i was called to work tomorrow morning so i cant catch up sorry my love twitchtv punnisenpai',
 'guilty of sobriety a bit of a borderline i was called to work early tomorrow so i cant catch up',
 'blaming sight for tardiness a little bit of borderlands i got called in early for work tomorrow so i cant make up time sorry my loves twitchtvpunnisenpai',
 'for blaming sight for tardiness a little bit of borderlands i got called in early for work tomorrow so i cant make up time sorry my loves twitchtvpunnisenpai',
 'why does like every man in borderlands have slicked back hair havent you heard of bangs you stupid asshol',
 'why like every man in border countries have you not heard of bangs you stupid asshol',
 'why like everyone else in the border countries have your hair fallen off have you not heard that you are stupid alien',
 'why does likeunk man in borderlands have slicked back hair or you heard of bangs you stupid asshol',
 'why beth does like every man in borderlands have she slicked that back hair haven t you heard enough of gray bangs you stupid asshol',
 'why does practically every man in france have slicked back hair havent you heard of bangs the greedy asshol',
 '45',
 'going to finish up borderlands 2 today ive got some new commands set up and am looking forward to a good stream starting in about am hour',
 'i will finish borderlands 2 today i have some new commands set up and am looking forward to a good stream start in about an hour',
 'im going to finish borderlands 2 today i have some new commands installed and im looking forward to a good stream',
 'going to finish up borderlands 2 today ive got some new events set up and am look forward to a good stream starting in about 20 hour',
 'going to finish finish cleaning up borderlands 2 today ive just got her some new commands set all up and am looking forward it to a good stream starting in about am hour',
 'going to finish up volume 2 today ive got some awesome server set up and is looking forward to a good stream starting in about am hour',
 'imma probably play some borderlands tps in a bit thatll be fun',
 'imma is probably playing a bit of borderland tps that will be fun',
 'imma will probably play some border tps in a bit its going to be fun',
 'imma probably play live borderlands tps in a bit thatll be fun',
 'for imma probably play some borderlands tps in a bit thatyer ll be a fun',
 'imma probably got some video tps in a bit thatll make fun',
 'one of our own profzeroo is live w borderlands 3 catch him here buffly2wmmip5 say streamer shouts in chat for a chance to be in a coming streamer_shouts shout out',
 'one of our own profzeroo is live w borderlands 3 catch him here buffly 2wmmip5 say streamer shouts in chat for a chance to be in an upcoming one streamer _ shouts shout out',
 'one of our own profzero live w borderlands 3 catch him here buffly 2wmmip5 say stream shouts in chat for a chat for a chance to be in a coming stream _ shouts shout out',
 'one of our own profzeroo is live borderlands 3 catch him here buffly2wmmip5 p say some shouts in chat a chance to be in a coming also shout out',
 'one of our shows own profzeroo is live via w at borderlands 3 and unk catch him here the buff ly to 2wmmip5 to say streamer shouts in chat for a chance to officially be in a series coming streamer_shouts 1 shout out',
 'one of its own movies is live w profzeroo 3 catch him from buffly2wmmip5 for streamer shouts in invitation or a chance to be out a coming all 3 invit',
 'fuck yessssssss',
 'fick yessssss',
 'fuck yessssssss',
 'fuck yessssssssunk',
 'a fuck yessssssss',
 'fuck you',
 'i hate that this easy mayhem modifier event on mayhem wont last forever this is the most fun ive had in the game since they added them horrible modifiers borderlands please give me the option to play mayhem 10 but turn the modifiers off pl',
 'i hate that this simple chaos modifier event on chaos wont last forever thats the most fun ive had in the game since they added terrible modifiers borderlands please give me the option to play chaos 10 but turn off the modifi',
 'i hate that this easy mayhem modifier event on mayhem wont last forever this is the most fun ive had in the game since they added them horrible modifiers borderlands please give me the option to play mayhem 10 but turn the modifiers off pl',
 'i hate saying this easy day 9 event on mayhem wont last forever this is the most fun ive had in the game since they added them horrible modifiers borderlands please give me some ability to play mayhem 10 but turn the modifiers off pl',
 'i hate thinking that this easy mayhem modifier event on total mayhem won t last forever this is the absolutely most ridiculous fun experience i ve had in the game almost since they added them horrible modifiers borderlands please do give me the option option to a play mayhem 10 but turn the modifiers off pl',
 'i hate that this easy horrible modifier event on game 10 last forever that is the best fun ive taken in the past until they added them horrible modifiers borderlands please send me the option to play mayhem 10 but turn the modifiers for pl',
 'grounded almost looked pretty cool even despite the borderlands tier unfunny writing until it became yet another survival crafting game i really cant wait for this shitty trend to di',
 'grounded looked cool despite the borderline unfunny writing until it became another survival crafting game i really cant wait for this crappy trend to di',
 'grosskreutz looked pretty cool even despite the unfunny spelling until it turned into another survival game i really cant wait for this crap trend to di',
 'grounded almost looked pretty cool here despite the borderlands tier unfunny writing until it became yet an survival crafting game i really cant wait for this shitty mod to di',
 'deep grounded almost looked pretty cool even despite the borderlands fifth tier unfunny writing format until ultimately it became yet another survival crafting mobile game i really can t wait for this shitty trend starting to di',
 'grounded almost was pretty cool even despite the top tier unfunny writing until we became yet another annoying crafting game i seriously cant wait on this shitty trend to di',
 'appreciate the sonic concepts praxis valenzuela and landaposas thread together in this talk multimodal listening soundwalks borderlands frameworks participatory action research and testimonios so many thoughtful and resonant intersections her',
 'appreciate the sound concepts practices that valenzuela and landaposas combine in this lecture multimodal listening soundwalks borderland frameworks participatory action research and testimonies so many thoughtful and resonant intersections her',
 'evaluate the sound concepts concepts of valensela and landa pozas together in this conversation multimodal listening walks border areas joint action studies etc so many amazing and resonant intersections her',
 'appreciate the sonic concepts praxis valenzuela and morenoposas have together in this talk multimodal listening soundwalks borderlands recordings participatory field research and testimonios so many thoughtful and resonant intersections her',
 'appreciate by the sonic electronic concepts praxis valenzuela and landa posas do thread together together in creating this talk multimodal visual listening digital soundwalks borderlands frameworks participatory action research interviews and testimonios so many thoughtful thoughts and resonant intersections reflected her',
 'appreciate the sonic conversations actions klein and landaposas brought together in our talk multimodal experiences soundwalks ethical frameworks participatory action practices and testimonios so many provocative and resonant intersections today',
 'borderlands how do i submit a complaint your ceo isnt paying his staff their bonus',
 'borderlands how can i file a complaint your ceo doesnt pay his employees their bonus',
 'borderlands how to file a complaint your ceo doesnt pay his employees bonus',
 'borderlands how did i submit a complaint your ceo isnt paying his competitors their bonus',
 'borderlands how do suppose i submit a complaint your ceo isnain t even paying his entire staff their bonus',
 'now how do i submit any complaint your ceo isnt offering his staff their bonus',
 'all the borderlands are fuckin trash',
 'all the borderlands are damn rubbish',
 'all the borderlands are fucking thrash',
 'all the borderlands shit fuckin trash',
 '35 all the borderlands are fuckin trash',
 'all the borderlands are fuckin stupid',
 'finally played through borderlands 3 the actual game play is great almost all guns feel fun and i never once felt like i needed to grind that story on the other hand all i will say is that im very much so looking forward to the eventual cutscene skip',
 'finally played by borderlands 3 the actual game is great almost all weapons feel funny and i never felt like i had to grind on the other hand all i will say is that i am very much looking forward to the eventual sequence skip',
 'this story on the other hand all i will say is that im looking forward to an occasional slip',
 'finally played through borderlands 3 the open game play is great almost all guns feel fun and i never once felt like i needed to grind the story on to another hand all i will say is that im very much so looking forward to its eventual cutscene skip',
 'finally played through borderlands 3 the actual game i play is great almost all guns feel fun and yet i never once felt much like someone i seriously needed to grind that pretty story on the other side hand all i will say is that im very damn much so forward looking forward to the eventual endless cutscene skip',
 'finally played through borderlands 5 the actual game play is great almost all guns were fun and i never once felt sure i needed to grind that story is the other hand but i will say now oh yesm very much so looking forward to the extended cutscene skip',
 'loving these new ghostlifestyle cans anyone else drink ghost',
 'i love these new ghostlifestyle cans everyone else drinks ghost',
 'love these new ghostlive cans does anyone else drink ghost',
 'loving these new ghostlifestyle cans anyone else drink ghost',
 'loving back these three new ghostlifestyle cans by anyone else else drink ghost',
 'do these new ghostlifestyleunk they want drink ghost',
 'come meet one of the lovely gaming goddess',
 'meet one of the lovely gambling goddess',
 'come meet one of the beautiful gods of gambl',
 'come to one of the lovely gaming goddess',
 '16 come meet one of the lovely gaming goddess',
 'come meet one of the lovely green goddess',
 'how the hell are we into halloween month alreadi',
 'how the hell are we already into halloween month',
 'how the hell are we already in halloween month',
 'how the hell are march into halloween month alreadi',
 'how the hell are pulling we into halloween month starting alreadi',
 'in the hell are we into halloween month alreadi',
 'what a bitch',
 'what a slut',
 'what a bitch',
 'what terrible bitch',
 'what a bitch',
 'what a miracl',
 'ok i am loving this also playing bombs over baghdad in anything gets me hype very borderlands like and the concept is a1',
 'ok im loving this also playing bombs over baghdad in something gives me a hype very borderlands like and the concept is a1',
 'ok i am loving this also playing bombs over baghad in anything gets me here very borderlands like and the concept is a1',
 'ok i am loving this also seeing take over baghdad in anything gets me hype very borderlands like and the concept is awesom',
 'ok sir i am loving this also just playing bombs over baghdad and in case anything gets its me hype i very borderlands like and the concept is a1',
 'ok i am loving this also playing bombs and earth in anything gets me hype very good rpg and the concept is a1',
 'just uninstalled all of my other games to make space for borderlands 3',
 'just uninstall all my other games to make room for borderlands 3',
 'just deleted all my other games to make room for borderlands 3',
 'just uninstalled all of my other games will make space for borderlands 3',
 'just uninstalled all other of my my other games to make space for watching borderlands 3',
 'just uninstalled all of all other games in make space for borderlands 3',
 'already loving bleeding edge what a clever game cross between overwatch borderlands and domination game mode cool a',
 'i love bleeding edge what a clever game crossroads of overwatch borderlands and domination game mode cool a',
 'cross between overwatch borderlands and domination game mode cool a',
 'already loving bleeding edge what a fun game cross between overwatch borderlands and xbox game mode cool a',
 'already also loving the bleeding edge what is a clever game cross between overwatch borderlands and future domination game mode 2016 cool out a',
 'already played bleeding edge what a clever game cross between fantasy borderlands non domination game mode playing a',
 'bioshock and borderlands coming to the switch bitch count me the fuck in',
 'bioshock and borderlands coming to the switch bitch count me the fuck in',
 'bioshock and borderlands coming to the switch bitch count me the fuck in',
 'bioshock and borderlands coming to the desert bitch count me the fuck in',
 'bioshock montana and other borderlands are coming to the switch bitch count me the fuck in',
 'bioshock and borderlands coming after your switch bitch count me the fuck in',

In [21]:
X=cv.fit_transform(stem_).toarray()
y=df['Sentiment']

In [22]:
from sklearn.model_selection import train_test_split

In [26]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

ValueError: Found input variables with inconsistent numbers of samples: [72741, 74681]